server:
  port: 8000

spring:
  application:
    name: EmployeeApplication



service:
  employee:
    url: https://dummy.restapiexample.com/api/v1
  useMockData: true

logging:
  level:
    com.example.rqchallenge.employees: DEBUG